# .github/workflows/deploy.yml

name: Reusable Deploy Script
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  deploy_step:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo TYK_URL: ${{ secrets.TYK_URL }
